CREATE USER repl_user REPLICATION LOGIN PASSWORD 'Qq12345';

CREATE DATABASE db_pt;

GRANT ALL PRIVILEGES ON DATABASE db_pt TO postgres;

\c db_pt;

CREATE TABLE IF NOT EXISTS Phone (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Email (
    id SERIAL PRIMARY KEY,
    email_address VARCHAR(100) NOT NULL
);
--ALTER USER postgres WITH PASSWORD 'Qq12345';CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';
